# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='encrypted_text',
            field=models.CharField(max_length=250),
        ),
    ]
