# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site02', '0002_auto_20160927_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
