# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site02', '0005_auto_20160928_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='authuser_ptr',
        ),
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
